PlaylistManager/Models/Playlist.cs
namespace PlaylistManager.Models;
using System.ComponentModel.DataAnnotations;

public class Playlist
{
    public int PlaylistId { get; set; }
    [Required(ErrorMessage = "You must give the playlist a name!")]
    public string Name { get; set; }
    public string ImageUrl { get; set; }
    public int Plays { get; set; }
    public List<PlaylistSong> JoinEntities { get; }
}

PlaylistManager/Controllers/PlaylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PlaylistManager.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PlaylistManager.Controllers;

public class PlaylistsController : Controller
{
    private readonly PlaylistManagerContext _db;
    public PlaylistsController(PlaylistManagerContext db)
    {
        _db = db;
    }
    public ActionResult Index()
    {
        List<Playlist> model = _db.Playlists.ToList();
        ViewBag.PageTitle = "View all playlists";
        return View(model);
    }

    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public ActionResult Create(Playlist playlist)
    {
        if (playlist.Name == null)
        {
            return View();
        }
        if (playlist.ImageUrl == null)
        {
            playlist.ImageUrl = "https://yt3.googleusercontent.com/ytc/AIf8zZT1nbQ7re2-12jCsO1JNGaYWTW1nrtSwmGoMobA1w=s900-c-k-c0x00ffffff-no-rj";
        }
        _db.Playlists.Add(playlist);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
        Playlist playlist = _db.Playlists
            .Include(playlist => playlist.JoinEntities)
            .ThenInclude(join => join.Song)
            .FirstOrDefault(playlist => playlist.PlaylistId == id);

        return View(playlist);
    }

    public ActionResult Edit(int id)
    {
        Playlist playlist = _db.Playlists.FirstOrDefault(playlist => playlist.PlaylistId == id);
        return View(playlist);
    }

    [HttpPost]
    public ActionResult Edit(Playlist playlist)
    {
        _db.Playlists.Update(playlist);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
        Playlist playlist = _db.Playlists.FirstOrDefault(p => p.PlaylistId == id);
        return View(playlist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        Playlist playlist = _db.Playlists.FirstOrDefault(p => p.PlaylistId == id);
        _db.Playlists.Remove(playlist);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult AddSong(int id)
    {
        Playlist playlist = _db.Playlists.FirstOrDefault(playlist => playlist.PlaylistId == id);
        ViewBag.SongId = new SelectList(_db.Songs, "SongId", "Name");
        return View(playlist);
    }

    [HttpPost]
    public ActionResult AddSong(Playlist playlist, int songId)
    {
        PlaylistSong? joinEntity = _db.PlaylistSongs.FirstOrDefault(join => (join.SongId == songId && join.PlaylistId == playlist.PlaylistId));
        if (joinEntity == null && songId != 0)
        {
            _db.PlaylistSongs.Add(new PlaylistSong() { SongId = songId, PlaylistId = playlist.PlaylistId });
            _db.SaveChanges();
        }
        return RedirectToAction("Details", new { id = playlist.PlaylistId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
        PlaylistSong joinEntry = _db.PlaylistSongs.FirstOrDefault(entry => entry.PlaylistSongId == joinId);
        _db.PlaylistSongs.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult Play(int id)
    {
        Playlist playlist = _db.Playlists.FirstOrDefault(playlist => playlist.PlaylistId == id);
        playlist.Plays += 1;
        _db.Playlists.Update(playlist);
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = playlist.PlaylistId });
    }
}

PlaylistManager/Views/Playlists/AddSong.cshtml
@model PlaylistManager.Models.Playlist

<h2>Add a song</h2>

<h4>Add a song to this playlist: @Model.Name</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.PlaylistId)

    @Html.Label("Pick a song")
    @Html.DropDownList("SongId")

    <input class="button" type="submit" value="Add" />
}

<p>@Html.ActionLink("Back to playlists", "Index")</p>

<button class="button">@Html.ActionLink("Home", "Index", "Home")</button>

PlaylistManager/Views/Playlists/Create.cshtml
@model PlaylistManager.Models.Playlist

<h4>Add a new playlist</h4>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    @Html.LabelFor(model => model.ImageUrl)
    @Html.TextBoxFor(model => model.ImageUrl)

    <input class="button" type="submit" value="Add new playlist" />
}

<p>@Html.ActionLink("Show all playlists", "Index")</p>

PlaylistManager/Views/Playlists/Delete.cshtml
@model PlaylistManager.Models.Playlist
<h2>Are you sure you want to delete this playlist?</h2>

<h3> Playlist: @Model.Name</h3>
@using (Html.BeginForm())
{
    <input class="button" type="submit" value="Delete" />
}
@Html.ActionLink("Back to playlist list", "Index")

PlaylistManager/Views/Playlists/Details.cshtml
@model PlaylistManager.Models.Playlist;
@using PlaylistManager.Models;

<h2>Playlist Details:</h2>
<h3>Name: @Model.Name</h3>
<img src=@Model.ImageUrl alt="Playlist image">
@if (@Model.JoinEntities.Count == 0)
{
    <p class="pl-details">This playlist does not contain any songs</p>
}
else
{
    <h3>Plays: @Model.Plays</h3>
    <div class="play-button">
    @using (Html.BeginForm("Play", "Playlists"))
    {
        @Html.Hidden("id", @Model.PlaylistId)
        <input class="button" type="submit" value="Play" />
    }
    </div>
    <h4>Songs in the playlist:</h4>
    <ul>
        @foreach (PlaylistSong join in Model.JoinEntities)
        {
            <div class="song-list">
                <li>@join.Song.Name</li>
                @using (Html.BeginForm("DeleteJoin", "Playlists"))
                {
                    @Html.Hidden("joinId", @join.PlaylistSongId)
                    <input class="button" type="submit" value="Remove" />
                }
            </div>
        }
    </ul>
}
<p>@Html.ActionLink("Edit playlist", "Edit", new { id = Model.PlaylistId })</p>
<p>@Html.ActionLink("Add a song to this playlist", "AddSong", new { id = Model.PlaylistId })</p>
<p>@Html.ActionLink("Delete playlist", "Delete", new { id = Model.PlaylistId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

PlaylistManager/Views/Playlists/Edit.cshtml
@model PlaylistManager.Models.Playlist

<h2>Edit</h2>

<h4>Edit this playlist: @Model.Name</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.PlaylistId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.ImageUrl)
    @Html.EditorFor(model => model.ImageUrl)

    <input class="button" type="submit" value="Update" />
}

<p>@Html.ActionLink("Back to playlists", "Index")</p>

PlaylistManager/Views/Playlists/Index.cshtml
@using PlaylistManager.Models;

<h1>Playlists</h1>

@if (@Model.Count == 0)
{
    <h3>No playlists have been created.</h3>
}

<div class="playlist-container">
    @foreach (Playlist playlist in Model)
    {
        <div class="card-container">
            <a href="/Playlists/Details/@playlist.PlaylistId">
                <div class="card" style="width: 18rem;">

                    <img src=@playlist.ImageUrl class="card-img-top" alt="Playlist image">
                    <div class="card-body">
                        <h5 class="card-title">@playlist.Name</h5>
                    </div>
                </div>
            </a>
        </div>
        @* <li>@Html.ActionLink($"{playlist.Name}", "Details", new { id = playlist.PlaylistId })</li>
    <img src=@playlist.ImageUrl alt="Playlist image" width="300px" /> *@
    }
</div>
<br />
<br />

<p>@Html.ActionLink("Add new playlist", "Create")</p>

@*
<a asp-controller="Playlists" asp-action="Details" asp-route-id="@playlist.PlaylistId">
<div class="card" style="width: 18rem;">
<img src=@playlist.ImageUrl class="card-img-top" alt="Playlist image">
<div class="card-body">
<h5 class="card-title">@playlist.Name</h5>
</div>
</div>
</a> *@